system:
  general_threads: 40
  heavy_threads: 10
  timeout: 7200
  storage_path: "./scans"
  # Ganti dengan Webhook Discord Anda (Opsional)
  discord_webhook: "" 

filter:
  extensions: "png,jpg,jpeg,gif,css,js,svg,ico,woff,mp4"